# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
authors = ["Laniakea Kamasylvia"]
categories = []
compiler = "0.12.0"
description = "This package introduces a labeling feature to Typst, inspired by the KOMA-Script's labeling environment. It offers a straightforward method to create lists with custom labels, providing a consistent and professional look to your documents."
disciplines = []
entrypoint = "src/lib.typ"
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
]
homepage = ""
keywords = []
license = "MIT"
name = "koma-labeling"
repository = "https://github.com/kamasylvia/typst-packages.git"
version = "0.1.0"

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
